# Como crear un array de numpy

np.reshape('datos', 'dimensiones', 'formato')
- np.reshape(datos, (dimensiones), 'C') --> Rellena por filas (default)
- np.reshape(datos, (dimensiones), 'F') --> Rellena por columnas

np.array() --> Rellena por filas dentro de la matriz

In [2]:
import numpy as np
mis_datos = np.arange(0, 20)

print(mis_datos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
m1 = np.reshape(mis_datos, (5,4), order='C')
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
m2 = np.reshape(mis_datos, (5,4), order='F')
m2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [5]:
m3 = np.array(mis_datos)
m3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
# Concepto POO, podemos aplicar directamente el método al objeto.
mis_datos.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
r1 = ["hola", "adios", "buenos dias"]
r2 = ["lunes", "martes", "miercoles"]
r3 = [1, 2, 3]

In [9]:
[r1, r2, r3]

[['hola', 'adios', 'buenos dias'], ['lunes', 'martes', 'miercoles'], [1, 2, 3]]

In [11]:
# Recordatorios: en un array solo se puede guardar un tipo de dato
# Está transformando los int a strings
np.array([r1,r2,r3])  

array([['hola', 'adios', 'buenos dias'],
       ['lunes', 'martes', 'miercoles'],
       ['1', '2', '3']], dtype='<U21')

---

# Diccionario

In [13]:
dicc1 = {'clave1':'valor1','clave2':'valor2','clave3':'valor3'}
dicc1['clave2']

'valor2'

In [16]:
dicc2 = {'españa': 'valor españa', 'francia': 'valor francia', 'alemania': 'valor alemania'}
dicc2['alemania']

'valor alemania'

---
