El objetivo será crear un dataframe con las ventas de nuestras 3 oficinas para los meses de enero, febrero y marzo.
- Crear una variable "ventas_enero" que contenga una lista de 3 números enteros aleatorios entre 100 y 500.
- Crear una variable "ventas_febrero" que contenga una lista de 3 números enteros aleatorios entre 100 y 500.
- Crear una variable "ventas_marzo" que contenga una lista de 3 números enteros aleatorios entre 100 y 500.
- Crear una variable "filas" que contenga esta lista de palabras: "ventas_enero", "ventas_febrero", "ventas_marzo".
- Crear una variable "columnas" que contenga esta lista de palabras: "oficina1", "oficina2", "oficina3".
- Crear una variable "ventas" que contenta una lista con los valores de ventas de enero, febrero y marzo.
- Crear un dataframe "datafame" que contenga las ventas, filas y columnas.
- Mediante print muestra el valor de "Las ventas de enero para la oficina 1 son de ..."

In [31]:
import pandas as pd
import numpy as np

In [32]:
ventas_enero = np.random.randint(100, 500, 3)
ventas_enero

array([104, 311, 255])

In [33]:
ventas_febrero = np.random.randint(100, 500, 3)
ventas_febrero

array([226, 163, 311])

In [34]:
ventas_marzo = np.random.randint(100, 500, 3)
ventas_marzo

array([207, 355, 454])

In [35]:
filas = ['ventas_enero', 'ventas_febrero', 'ventas_marzo']
filas

['ventas_enero', 'ventas_febrero', 'ventas_marzo']

In [36]:
columnas = ['oficina1', 'oficina2', 'oficina3']
columnas

['oficina1', 'oficina2', 'oficina3']

In [37]:
ventas = [ventas_enero, ventas_febrero, ventas_marzo]
ventas

[array([104, 311, 255]), array([226, 163, 311]), array([207, 355, 454])]

In [38]:
dataframe = pd.DataFrame(ventas, index=filas, columns=columnas)
print(dataframe)

                oficina1  oficina2  oficina3
ventas_enero         104       311       255
ventas_febrero       226       163       311
ventas_marzo         207       355       454


In [41]:
ventas_enero_oficina1 = dataframe['oficina1']['ventas_enero']

In [42]:
print(f'Las ventas de enero para la oficina 1 son de {ventas_enero_oficina1}')

Las ventas de enero para la oficina 1 son de 104
