In [3]:
import numpy as np

In [5]:
lista = [1, 2, 3, 4, 5]
array = np.array(lista)
array

array([1, 2, 3, 4, 5])

In [6]:
lista2 = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(lista2)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---
Numpy arrays - arange, zeros, ones, linspace, eye

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2, 10, 2) 

array([2, 4, 6, 8])

In [11]:
np.zeros(5) # Array de ceros de tamaño 5

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5)) # Array de ceros de tamaño 5x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(5) # Array de 5x1 con todos los valores 1

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((2,2)) # Array de 2x2 con todos los valores 1

array([[1., 1.],
       [1., 1.]])

In [16]:
np.linspace(5, 10, 11) # 10 elementos entre 5 y 10

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [17]:
np.eye(3) # Matriz identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

---
Numpy array - números aleatorios - rand y randn

In [22]:
np.random.rand(3) # genera un vector de 3 elementos aleatorios uniformemente distribuidos en el intervalo [0,1)

array([0.97461128, 0.25978134, 0.92728546])

In [23]:
np.random.rand(3, 4) # genera un array de 3 filas y 4 columnas con valores aleatorios entre 0 y 1

array([[0.78369521, 0.05919294, 0.57879305, 0.17568485],
       [0.50027575, 0.13971673, 0.35087191, 0.51962339],
       [0.86580856, 0.66872369, 0.30186979, 0.77591004]])

In [26]:
np.random.randn(4) # generar 4 números aleatorios normales con media cero y desviación estándar 1 

array([-1.08161551, -1.64364318, -0.00734268, -0.8953266 ])

In [25]:
np.random.randn(4, 5) # generar matriz de 4 filas y 5 columnas con valores aleatorios normales (normal distribución)

array([[-0.55160568,  0.82128123,  1.97580051,  0.2384993 , -0.08428435],
       [-0.1860091 ,  0.78462494, -0.70290115,  0.45460086,  0.3748837 ],
       [ 0.65278351, -0.7145699 , -0.33677768, -1.03134803, -2.2746481 ],
       [-1.45786304, -1.18586234,  0.24823365, -0.10359886, -0.58556293]])

---
Numpy arrays - números aleatorios enteros, randint

In [27]:
np.random.randint(1,20) # genera un número aleatorio entre 1 y 20

9

In [28]:
np.random.randint(1,20) # genera un número aleatorio entre 1 y 20

2

In [30]:
np.random.randint(0, 100, size=5) # generar 5 números aleatorios entre 0 y 100

array([37, 50, 94, 21, 79])

In [29]:
np.random.randint(0, 100, size=(10, 10)) # 10 x 10 matriz de números aleatorios

array([[63, 67,  9, 98, 90, 97, 93, 89, 92, 60],
       [66, 19, 44, 28, 88, 66, 21, 58, 42, 52],
       [51, 83, 24, 11,  8, 67, 35, 16, 13, 61],
       [85,  8, 16, 87, 80, 10,  4, 20, 75, 59],
       [45, 51, 18, 32,  7, 10, 81, 28, 18, 25],
       [ 9, 59, 74, 16, 51, 70, 13,  7, 48, 22],
       [81, 26, 73, 63, 97, 28,  2, 44, 18, 39],
       [39, 76, 96, 74,  4, 35, 53,  1, 69, 56],
       [57, 85, 97, 59, 99, 72, 26, 26,  3, 90],
       [80, 32,  3, 44, 34, 28, 95, 43, 60, 70]])

---
Numpy array - reshape

In [32]:
array = np.random.randint(0, 100, size=25)
array

array([88, 37, 31, 99, 40, 45, 23, 38, 32, 43, 22, 66, 92, 33, 56, 53,  6,
       99, 70, 94, 48, 69, 77,  6, 82])

In [34]:
matriz = array.reshape(5,5) 
matriz

array([[88, 37, 31, 99, 40],
       [45, 23, 38, 32, 43],
       [22, 66, 92, 33, 56],
       [53,  6, 99, 70, 94],
       [48, 69, 77,  6, 82]])

---
Numpy array - max y min

In [36]:
array = np.random.randint(0, 100, size=50)
array

array([70, 41, 42, 86, 23, 95, 88, 43, 69, 44, 89, 42, 62,  8, 79, 93, 49,
       24, 92, 96, 81, 85, 28, 83, 40, 88, 34,  6,  0, 35, 52, 69, 12,  5,
       80, 49, 59, 14, 54, 78, 60,  6, 81, 57, 65, 39,  4, 70, 82, 88])

In [43]:
valor_max = array.max()
print(valor_max)

96


In [47]:
posicion_valor_max = np.argmax(array)
print(posicion_valor_max)

np.int64(19)

In [45]:
valor_min = array.min()
print(valor_min)

0


In [49]:
posicion_valor_min = np.argmin(array)
print(posicion_valor_min)

28


---
Numpy array - indexacion en arrays

In [51]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
print(array[0])

0


In [54]:
print(array[-1])

9


In [56]:
array[2:4]

array([2, 3])

In [57]:
array[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
array[:4]

array([0, 1, 2, 3])

In [60]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
array2[0] = 100
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [63]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---
Numpy - Indexacion en arrays de 2 o más dimensiones

In [64]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
array[0]

array([1, 2, 3])

In [67]:
array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
array[1][2]

np.int64(6)

In [76]:
array[:,0] # selecciona la columna 0 de la matriz

array([1, 4, 7])

---
Numpy - Seleccionar elementos de un array según una condición


In [79]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
condicion = array > 5
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [82]:
array[condicion]

array([6, 7, 8, 9])

In [83]:
array[array < 5]

array([0, 1, 2, 3, 4])

In [84]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

---
Numpy - Operaaciones sobre los arrays

In [85]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
array + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [90]:
array2 = np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [91]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [93]:
array2 * array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [94]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [95]:
np.max(array)

np.int64(9)