- Crear una lista de número secuenciales con el valor mínimo de 10 y el valor máximo 39
- Convierte esta lista en una lista o matriz de 2 dimensiones (3 filas por 10 columnas)
- Muestra por pantalla el valor del elemento de la esquina superior derecha de la matriz

In [1]:
import numpy as np

In [4]:
lista = np.arange(10,40)
lista

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [6]:
lista = lista.reshape(3,10)
lista

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [7]:
lista[0,9]

np.int64(19)

---

- Crear un array de una dimensión con 9 valores enteros aleatorios entre 0 y 100
- Convierte ese arrat en una matriz de 2 dimensiones (3 filas y 3 columnas)
- Muestra por pantalla el valor del elemento de la matriz de la esquina inferior derecha

In [10]:
array = np.random.randint(1, 100, 9)
array

array([ 7, 83, 15, 80, 68, 23, 69, 80, 45])

In [12]:
matriz = array.reshape(3,3)
matriz

array([[ 7, 83, 15],
       [80, 68, 23],
       [69, 80, 45]])

In [15]:
matriz[2][2]

np.int64(45)